baseURL = "https://realnikolaj.github.io/t8g1-skylab/"
title = "Hosting, deployment and infrastructure services"
description = "At IT@Skylab administrators develop and monitor critical business services and infrastructe"
relativeURLs = true
theme = "theme"
[params]
    authors = ["Nikolaj S. Povlsen, Saif, Emin"]
    notebook = "/explainer-notebook.html"
    data = "https://doc.opensuse.org/"
    github = "https://github.com/realnikolaj/t8g1-skylab"
    [[params.nav]]
        label = "Group vm"
        link = "/Group-vm"
    [[params.nav]]
        label = "Saif vm"
        link = "/Saif-vm"
    [[params.nav]]
        label = "Nikolaj vm"
        link = "/Nikolaj-vm"
    [[params.nav]]
        label = "Emin vm"
        link = "/Emin-vm"
    [[params.nav]]
        label = "About"
        link = "/about"



